### ISSUE TITLE
No such file or directory: './data/performance/Performance_2024-10-23.csv

### ISSUE THREAD

**Issue by suchi-thamarai** [lunapapa-finland/Future-Trading-Analysis#1]
Hi,

This project is really good. Thanks for helping people.

I m getting this error while runnng `make report` as per the READ ME.

Kindly update the README for the steps to generate /data/performance/Performance_2024-10-23.csv

Many Thanks

**Comment by lunapapa-finland** [comment]
Hi that is the csv records about your intraday trade. Depending on the platform, it will be different when you download it.  You can either twist a little bit of the code to adapt your platform specific trading record in CSV format, or you can change the record you downloaded to the format like below. Have fun. 
![Screenshot 2024-12-21 at 15 22 21](https://github.com/user-attachments/assets/dd4a711c-0817-46fe-bbeb-f2f99c2dd121)

**Comment by selvanponraj** [comment]
thanks for explanation. which platform do you use?
